# Generated by Django 2.2.13 on 2020-09-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200924_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
